#!/usr/bin/env python3
"""
setup_model_paths.py - Auto-generate extra_model_paths.yaml for WSL/Windows model sharing
Automatically detects Windows drives and common model locations
"""

import os
import sys
from pathlib import Path

# WSL mount point for Windows drives
WSL_MNT_BASE = Path("/mnt")

# Common Windows paths for AI models (relative to drive root)
COMMON_MODEL_PATHS = [
    # ComfyUI installations
    "ComfyUI/models",
    "ComfyUI_windows/models",
    "AI/ComfyUI/models",

    # Stable Diffusion WebUI (A1111/Forge)
    "stable-diffusion-webui/models",
    "sd-webui/models",
    "AI/stable-diffusion-webui/models",

    # Common AI model folders
    "AI/models",
    "Models/AI",
    "StableDiffusion/models",

    # User folders
    "Users/{user}/AI/models",
    "Users/{user}/ComfyUI/models",
    "Users/{user}/stable-diffusion-webui/models",
]

# YAML template
YAML_TEMPLATE = '''# Auto-generated extra_model_paths.yaml
# Generated by setup_model_paths.py for WSL/Windows model sharing
# Edit paths as needed

{configs}
'''

CONFIG_TEMPLATE = '''
{name}:
    base_path: {base_path}
    is_default: {is_default}
    checkpoints: {checkpoints}
    text_encoders: |
        {text_encoders}
    clip_vision: {clip_vision}
    configs: {configs}
    controlnet: {controlnet}
    diffusion_models: |
        {diffusion_models}
    embeddings: {embeddings}
    loras: {loras}
    upscale_models: {upscale_models}
    vae: {vae}
'''

def get_windows_username():
    """Try to detect Windows username from common paths"""
    for drive in ['c', 'd', 'e']:
        users_path = WSL_MNT_BASE / drive / "Users"
        if users_path.exists():
            for user_dir in users_path.iterdir():
                if user_dir.is_dir() and user_dir.name not in ['Public', 'Default', 'Default User', 'All Users']:
                    return user_dir.name
    return None

def find_model_paths():
    """Find all valid model paths on Windows drives"""
    found_paths = []
    windows_user = get_windows_username()

    # Check each potential Windows drive
    for drive in ['c', 'd', 'e', 'f', 'g']:
        drive_path = WSL_MNT_BASE / drive
        if not drive_path.exists():
            continue

        for rel_path in COMMON_MODEL_PATHS:
            # Replace {user} placeholder
            if "{user}" in rel_path and windows_user:
                rel_path = rel_path.format(user=windows_user)
            elif "{user}" in rel_path:
                continue

            full_path = drive_path / rel_path
            if full_path.exists() and full_path.is_dir():
                found_paths.append(full_path)

    return found_paths

def detect_model_structure(base_path: Path) -> dict:
    """Detect the model folder structure"""
    structure = {
        'checkpoints': 'checkpoints',
        'text_encoders': 'text_encoders\n        clip',
        'clip_vision': 'clip_vision',
        'configs': 'configs',
        'controlnet': 'controlnet',
        'diffusion_models': 'diffusion_models\n        unet',
        'embeddings': 'embeddings',
        'loras': 'loras',
        'upscale_models': 'upscale_models',
        'vae': 'vae',
    }

    # Check for A1111/Forge style structure
    if (base_path / "Stable-diffusion").exists():
        structure['checkpoints'] = 'Stable-diffusion'
        structure['configs'] = 'Stable-diffusion'
    if (base_path / "VAE").exists():
        structure['vae'] = 'VAE'
    if (base_path / "Lora").exists():
        structure['loras'] = 'Lora\n        LyCORIS'
    if (base_path / "ESRGAN").exists():
        structure['upscale_models'] = 'ESRGAN\n        RealESRGAN\n        SwinIR'
    if (base_path / "ControlNet").exists():
        structure['controlnet'] = 'ControlNet'

    return structure

def generate_config(name: str, base_path: Path, is_default: bool = False) -> str:
    """Generate YAML config for a model path"""
    structure = detect_model_structure(base_path)

    return CONFIG_TEMPLATE.format(
        name=name,
        base_path=str(base_path),
        is_default='true' if is_default else 'false',
        **structure
    )

def main():
    print("=" * 50)
    print("ComfyUI Model Path Setup for WSL/Windows")
    print("=" * 50)
    print()

    # Find model paths
    print("[INFO] Scanning for Windows model folders...")
    found_paths = find_model_paths()

    if not found_paths:
        print("[WARN] No model folders found automatically.")
        print()
        print("Please enter your Windows model path manually.")
        print("Example: /mnt/d/AI/models or /mnt/c/Users/YourName/ComfyUI/models")
        print()

        while True:
            user_path = input("Enter path (or 'skip' to create template): ").strip()
            if user_path.lower() == 'skip':
                break
            path = Path(user_path)
            if path.exists():
                found_paths.append(path)
                another = input("Add another path? (y/n): ").strip().lower()
                if another != 'y':
                    break
            else:
                print(f"[ERROR] Path not found: {path}")

    # Generate configs
    configs = []
    for i, path in enumerate(found_paths):
        name = f"windows_{path.parts[2]}_{i}" if len(path.parts) > 2 else f"windows_{i}"
        # Clean up name
        name = name.replace("-", "_").replace(" ", "_")
        is_default = (i == 0)  # First found path is default

        print(f"[FOUND] {path}")
        configs.append(generate_config(name, path, is_default))

    if not configs:
        # Create template config
        configs.append('''
# Template - edit with your actual paths
windows_models:
    base_path: /mnt/d/AI/models  # <-- Change this!
    is_default: true
    checkpoints: checkpoints
    text_encoders: |
        text_encoders
        clip
    clip_vision: clip_vision
    configs: configs
    controlnet: controlnet
    diffusion_models: |
        diffusion_models
        unet
    embeddings: embeddings
    loras: loras
    upscale_models: upscale_models
    vae: vae
''')

    # Write YAML file
    output_path = Path(__file__).parent / "extra_model_paths.yaml"
    yaml_content = YAML_TEMPLATE.format(configs='\n'.join(configs))

    with open(output_path, 'w') as f:
        f.write(yaml_content)

    print()
    print("=" * 50)
    print(f"[SUCCESS] Created: {output_path}")
    print("=" * 50)
    print()
    print("Model paths configured:")
    for path in found_paths:
        print(f"  - {path}")
    print()
    print("Edit extra_model_paths.yaml if you need to adjust paths.")
    print()

if __name__ == "__main__":
    main()
